ALTER TABLE REFINED_DEV.BEDROCK.YESWANTH_TEST
ADD
	TIME_STAMP_TRY_UTC	TIMESTAMP_NTZ,
	TIME_STAMP_TRY_CST	TIMESTAMP_NTZ,
	ROLL_NUMBER custom_d_type
;
UPDATE REFINED_DEV.BEDROCK.YESWANTH_TEST REF
SET REF.TIME_STAMP_TRY_UTC = RAW.TIME_STAMP_TRY_UTC
,REF.TIME_STAMP_TRY_CST = RAW.TIME_STAMP_TRY_CST
,REF.ROLL_NUMBER custom_d_type = RAW.ROLL_NUMBER custom_d_type
FROM RAW_DEV.BEDROCK.YESWANTH_TEST RAW 
 WHERE REF.ID = RAW.ID;