ALTER TABLE REFINED_DEV.BEDROCK.YESWANTH_TEST
ADD
	ROLL_NUMBER custom_d_type,
	TIME_STAMP_TRY_UTC	TIMESTAMP_NTZ,
	TIME_STAMP_TRY_CST	TIMESTAMP_NTZ
;
UPDATE REFINED_DEV.BEDROCK.YESWANTH_TEST REF
SET REF.ROLL_NUMBER custom_d_type = RAW.ROLL_NUMBER custom_d_type
,REF.TIME_STAMP_TRY_UTC = RAW.TIME_STAMP_TRY_UTC
,REF.TIME_STAMP_TRY_CST = RAW.TIME_STAMP_TRY_CST
FROM RAW_DEV.BEDROCK.YESWANTH_TEST RAW 
 WHERE REF.ID = RAW.ID;