MERGE INTO REFINED_DEV.BEDROCK.YESWANTH_TEST TGT 
USING ( SELECT 
NAME
,TIME_Z::TIMESTAMP_NTZ AS TIME_Z_UTC
,CONVERT_TIMEZONE('UTC', 'America/Chicago', TIME_Z::TIMESTAMP_NTZ) AS TIME_Z_CST
,CAST("ROLL_NUMBER" AS INTEGER)+1 AS ROLL_NUMBER
,TIME_STAMP_TRY::TIMESTAMP_NTZ AS TIME_STAMP_TRY_UTC
,CONVERT_TIMEZONE('UTC', 'America/Chicago', TIME_STAMP_TRY::TIMESTAMP_NTZ) AS TIME_STAMP_TRY_CST FROM RAW_DEV.BEDROCK.YESWANTH_TEST 
WHERE _FIVETRAN_SYNCED::TIMESTAMP_NTZ > (SELECT nvl(max(FIVETRAN_SYNCED_UTC ),to_timestamp("2000-01-01")) FROM REFINED_DEV.BEDROCK.YESWANTH_TEST)) SRC
ON src.ID = tgt.ID
WHEN MATCHED THEN UPDATE SET
tgt.NAME = src.NAME
,tgt.TIME_Z_UTC = src.TIME_Z_UTC
,tgt.TIME_Z_CST = src.TIME_Z_CST
,tgt.ROLL_NUMBER = src.ROLL_NUMBER
,tgt.TIME_STAMP_TRY_UTC = src.TIME_STAMP_TRY_UTC
,tgt.TIME_STAMP_TRY_CST = src.TIME_STAMP_TRY_CST
WHEN NOT MATCHED THEN INSERT (
NAME
,TIME_Z_CST
,ROLL_NUMBER
,TIME_STAMP_TRY_CST
)
VALUES(
src.NAME
,src.TIME_Z_CST
,src.ROLL_NUMBER
,src.TIME_STAMP_TRY_CST
);


INSERT INTO REFINED_DEV.BEDROCK.YESWANTH_TEST_ARCHIVE (
NAME
,TIME_Z_CST
,ROLL_NUMBER
,TIME_STAMP_TRY_CST) 
SELECT
NAME
,TIME_Z_CST
,ROLL_NUMBER
,TIME_STAMP_TRY_CST
FROM REFINED_DEV.BEDROCK.YESWANTH_TEST
WHERE REFINED_LOAD_TIME_CST > (SELECT nvl(max(REFINED_LOAD_TIME_CST),to_timestamp('2000-01-01')) FROM REFINED_DEV.BEDROCK.YESWANTH_TEST_ARCHIVE);